### ISSUE TITLE
Checklist for Release

### ISSUE THREAD

**Issue by cnguy** [cnguy/strawpoll#4]
- [ ] Backend
  - [x] Core Poll API
  - [x] Core Answer API
  - [x] IP Addr Checking
    - [x] Backend
    - [x] Frontend
- [ ] Validation Logic
  - [ ] Client
  - [ ] Server
- [ ] UI
  - [ ] Core
  - [ ] Code Re-use
- [ ] Handle deployment-related stuffs (the IndexEndpoints is just a hack?)
